### ISSUE TITLE
title and h1 treated the same as `=`

### ISSUE THREAD

**Issue by emmanuelbernard** [maxandersen/gdoc2adoc#12]
Google Docs have `Title` and `Heading n` formatting.

I imagine the formal way to map it would be:
- Title => `=`
- Heading 1 => `==`
- Heading 2 => `===`

etc.

At the moment, both Title and Heading 1 are mapped `=` which makes the document incorrect.
@maxandersen do you agree to change the mapping as described?

**Comment by maxandersen** [comment]
makes sense, reason for the current mapping is that is how the previous markdown stuff worked.

**Comment by maxandersen** [comment]
PR #14 merged.
